### ISSUE TITLE
Null point exception on opening dialog

### ISSUE THREAD

**Issue by VimbaTheFish** [Ylinor/Storyteller#1]
https://pastebin.com/3N4LfqZv

spongeforge-1.12.2-2705-7.1.0-BETA-3148

Tried command /dialog 1

Config (copied from github): https://pastebin.com/QCj8D69y

**Comment by Hbeau** [comment]
Hi @SkyFire55 ,
Thank you for your feedback ! The problem was on our side and we fixed it. This was due to a wrong use of  the `Injection system`. Please try the new [release](https://github.com/Ylinor/Storyteller/releases).  
  
We remain available for any further questions or suggestions.

**Comment by VimbaTheFish** [comment]
Thanks for quick response! It works now, but I see debug in console: https://i.imgur.com/0fvHPwq.png
If it's planned, so it's ok.
As far as it works now, issue can be closed.

**Comment by VimbaTheFish** [comment]
Minor bug before closing - using /dialoge 1 opens dialoge with id=2. /dialoge 0 opens dialoge 1.
