### ISSUE TITLE
Suggestion: /dialoge <id> <playername>

### ISSUE THREAD

**Issue by VimbaTheFish** [Ylinor/Storyteller#2]
Command, which will allow to open dialoges for players from console will be very useful for servers with NPC plugin installed. It will be helpful when u don't want players to open dialogs via commands, and want to show them dialogs when they interact with something.

**Comment by Hbeau** [comment]
Thank you for your nice feature idea. We update the command now you can call `/dialog <id> [player] ` and set a player name or a selector like `@a` or  `@p` for example.

This feature is available in the version 0.1.2 and above.
