### ISSUE TITLE
Create a command that triggers a specific NPC dialog

### ISSUE THREAD

**Issue by obr-09** [Ylinor/Storyteller#6]
With this command, one should be able to trigger the dialog a NPC would give if he were right clicked.

**Comment by Hbeau** [comment]
for now we will use [this](https://forums.spongepowered.org/t/snowman-npcs-v3-0-0-easiest-and-best-npc-plugin/18273) sponge plugin to manage NPC. insted we need a command who load the appropriate dialog for a npc example : `/trigger<npc name>`
